# version: '3.8'
services:
  netcore1: 
    hostname: netcore1
    build: ./app/
    restart: always
    environment:
      - OTLP_ENDPOINT_URL=http://olgtm:4317
    labels:
      - logging=promtail
    networks:
      - mynetwork

  netcore2:
    hostname: netcore2
    image: aspnetcore-metrics-learning-netcore1:latest
    restart: always
    environment:
      - OTLP_ENDPOINT_URL=http://olgtm:4317
    labels:
      - logging=promtail
    depends_on:
      - netcore1
    networks:
      - mynetwork

  netcore3:
    hostname: netcore3
    image: aspnetcore-metrics-learning-netcore1:latest
    restart: always
    environment:
      - OTLP_ENDPOINT_URL=http://olgtm:4317
    labels:
      - logging=promtail
    depends_on:
      - netcore1
    networks:
      - mynetwork

  olgtm:
    container_name: olgtm
    image: grafana/otel-lgtm
    ports:
      - 3000:3000  # grafana (admin, admin)
      - 9090:9090  # prometheus
      - 4318:4318  # collector http
      - 4317:4317  # collector grp
    networks:
      - mynetwork

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./jenkins/jenkins_home/:/var/jenkins_home/
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    networks:
      - mynetwork
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  ## for this container (sonarqube), require execute this command on host machine:
  ## sudo sysctl -w vm.max_map_count=262144
  sonarqube:
    container_name: sonarqube
    image: sonarqube:8-community
    depends_on:
      - postgres-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-db/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
    networks: 
      - mynetwork

  promtail-agent:
    container_name: promtail-agent
    image: grafana/promtail:latest
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      LOKI_USERNAME: admin
      LOKI_PASSWORD: gatewayzin-loki
    command: ["-config.file=/etc/promtail/config.yml", "-config.expand-env=true"]
    networks:
      - mynetwork

  postgres-db:
    container_name: postgres-test
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes: 
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    networks: 
      - mynetwork

  adminer:
    container_name: adminer-test
    image: adminer
    restart: always
    environment: 
      ADMINER_DESIGN: galkaev
    networks: 
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp: